=== bbabum/blood-bank/bloodstock.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.javatpoint.com"
xmlns="http://www.javatpoint.com"
elementFormDefault="qualified">
<xs:element name="stock">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="bloodgroup" type="xs:string"/>
            <xs:element name="requirement" type="xs:string"/>
            <xs:element name="quantity" type="xs:int"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="state" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== bbabum/blood-bank/bloodstock.xml
<?xml version="1.0"?>
<stock xmlns="http://www.javatpoint.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.javatpoint.com E:\Blood Bank Management\bloodstock.xsd">
    <bloodgroup>B+</bloodgroup>
    <requirement>Plasma</requirement>
    <quantity>2</quantity>
    <city>Madurai</city>
    <state>Tamilnadu</state>

    <bloodgroup>A+</bloodgroup>
    <requirement>Blood</requirement>
    <quantity>3</quantity>
    <city>Salem</city>
    <state>Tamilnadu</state>
</stock>
